#!/bin/sh

target_dir=$(cargo metadata --format-version 1 | jq -r '.target_directory')

dd if=/dev/zero of=fat.img bs=1k count=1440
mformat -i fat.img -f 1440 ::
mmd -i fat.img ::/EFI
mmd -i fat.img ::/EFI/BOOT
mcopy -i fat.img ${target_dir}/aarch64-unknown-uefi/debug/loader.efi ::EFI/BOOT/BOOTX64.EFI
